version: "3"
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/mcc:cached
      - /usr/mcc/node_modules
    env_file:
      - .env
    environment:
      - PORT=8000
